const plantData = {
  data: [
    {
      id: 47,
      latin: "Cissus Rhombifolia",
      common: "Ellen Danica",
      category: "Hanging",
      tempmax: 82.4,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Less Frequent",
      image:
        "https://cb.scene7.com/is/image/Crate/TrailingFicusHangingPlantSSS21/$web_pdp_main_carousel_med$/201019091947/faux-trailing-ficus-hanging-plant-in-pot.jpg",
    },
    {
      id: 3006,
      latin: "Aeschynanthus Radicans",
      common: "Twisted Lipstick",
      category: "Hanging",
      tempmax: 75,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Average",
      image:
        "https://www.moneyquest.com.au/wp-content/uploads/2022/02/Lipstick-plant.jpg",
    },
    {
      id: 56,
      latin: "Cissus Rhombifolia",
      common: "Grape Ivy",
      category: "Hanging",
      tempmax: 82.4,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Less Frequent",
      image:
        "https://m.media-amazon.com/images/I/61Bn0LBgFML.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    },
    {
      id: 63,
      latin: "Chlorophytum Comosum",
      common: "Spider Plant",
      category: "Hanging",
      tempmax: 82.4,
      tempmin: 41,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Frequent",
      image: "https://m.media-amazon.com/images/I/51wtlZUB5ML._AC_.jpg",
    },
    {
      id: 93,
      latin: "Epipremnum Aureum",
      common: "Marble Queen",
      category: "Hanging",
      tempmax: 53.6,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Frequent",
      image:
        "https://img.kwcdn.com/product/Fancyalgo/VirtualModelMatting/ac9a58e59916e30b604ce7b7394d9a1b.jpg?imageView2/2/w/800/q/70",
    },
    {
      id: 103,
      latin: "Hedera Canariensis",
      common: "Algerian Ivy",
      category: "Hanging",
      tempmax: 41,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Frequent",
      image:
        "https://dubaigardencentre.ae/getimage/products/hederahelix_i41323_prod_img_1_copy.jpg",
    },
    {
      id: 104,
      latin: "Epipremnum Aureum",
      common: "Golden Pothos",
      category: "Hanging",
      tempmax: 53.6,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Average",
      image: "https://m.media-amazon.com/images/I/41IkfFhdJTL._AC_.jpg",
    },
    {
      id: 0,
      latin: "Aeschynanthus Lobianus",
      common: "Lipstick",
      category: "Hanging",
      tempmax: 89.6,
      tempmin: 57.2,
      ideallight: "Bright Light",
      toleratedlight: "Direct Sunlight",
      watering: "Less Frequent",
      image:
        "https://foliadesign.ca/cdn/shop/products/DSC_9573_2048x.jpg?v=1663603416",
    },
    {
      id: 115,
      latin: "Hedera Helix",
      common: "English Ivy",
      category: "Hanging",
      tempmax: 41,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Average",
      image:
        "https://www.provenwinners.com/sites/provenwinners.com/files/imagecache/500x500/ifa_upload/hedera_glacier_mono.jpg",
    },
    {
      id: 1,
      latin: "Adiantum Raddianum",
      common: "Maindenhair",
      category: "Fern",
      tempmax: 86,
      tempmin: 53.6,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Frequent",
      image:
        "https://botanically.nl/wp-content/uploads/2020/11/adiantum-capilius-veneris.jpg",
    },
    {
      id: 61,
      latin: "Asplenium Nidus",
      common: "Birdnest Fern",
      category: "Fern",
      tempmax: 82.4,
      tempmin: 59,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Frequent",
      image: "https://m.media-amazon.com/images/I/81fqLV0QulL._AC_SL1500_.jpg",
    },
    {
      id: 64,
      latin: "Didymochlaena Truncatula",
      common: "Tree Maindenhair Fern",
      category: "Fern",
      tempmax: 41,
      tempmin: 20,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Diffused",
      watering: "Frequent",
      image:
        "https://dartfrogconnection.com/media/catalog/product/cache/cfa8c0fc552e61495db3610f5747c90a/d/i/didymochlaena_truncatula_0154_2nd.jpg",
    },
    {
      id: 79,
      latin: "Cyrtomium Falcatum",
      common: "Holly Fern",
      category: "Fern",
      tempmax: 41,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Average",
      image:
        "https://www.plantvine.com/plants/Cyrtomium-falcatum-large-holly-fern-copy.jpg",
    },
    {
      id: 124,
      latin: "Pellaea Falcata",
      common: "Sickle Fern",
      category: "Fern",
      tempmax: 77,
      tempmin: 53.6,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Frequent",
      image:
        "https://i.etsystatic.com/11587994/r/il/80650d/978886120/il_fullxfull.978886120_q8p1.jpg",
    },
    {
      id: 152,
      latin: "Pteris Cretica Parkeri",
      common: "Cretan Brake",
      category: "Fern",
      tempmax: 82.4,
      tempmin: 53.6,
      ideallight: "Bright Light",
      toleratedlight: "Partial Shade",
      watering: "Frequent",
      image:
        "https://www.tropicopia.com/house-plant/originals/Pteris%20cretica%20Parkeri%2006.jpg",
    },
    {
      id: 28,
      latin: "Allamanda Nerifolia",
      common: "Golden Trumpet",
      category: "Flower",
      tempmax: 50,
      tempmin: 20,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Average",
      image:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Flowers_of_Allamanda_cathartica_in_West_Bengal%2C_India.jpg/1024px-Flowers_of_Allamanda_cathartica_in_West_Bengal%2C_India.jpg",
    },
    {
      id: 42,
      latin: "Bougainvillea",
      common: "Paper Flower",
      category: "Flower",
      tempmax: 89.6,
      tempmin: 50,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Average",
      image:
        "https://assets.wfcdn.com/im/70873102/resize-h445%5Ecompr-r85/2479/247940644/Bougainvillea+Hanging+Basket+Arrangement+in+Basket.jpg",
    },
    {
      id: 119,
      latin: "Mandevilla X",
      common: "Dipladenia",
      category: "Flower",
      tempmax: 50,
      tempmin: 20,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Frequent",
      image:
        "https://creativeplantdesigns.com/wp-content/uploads/2015/09/MandevillaTrellis10.jpg",
    },
    {
      id: 122,
      latin: "Hedychium Coronarium",
      common: "White Ginger",
      category: "Flower",
      tempmax: 50,
      tempmin: 20,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Frequent",
      image:
        "https://assets.wfcdn.com/im/02060305/resize-h445%5Ecompr-r85/8834/88341230/12%22+Potted+Hedychium+Coronarium+Spring+Artificial+Floral+Arrangement.jpg",
    },
    {
      id: 138,
      latin: "Phalaenopsis X",
      common: "Phalaenopsis Orchid",
      category: "Flower",
      tempmax: 82.4,
      tempmin: 53.6,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Less Frequent",
      image:
        "https://assets.wfcdn.com/im/20974951/resize-h445%5Ecompr-r85/2414/241404008/Handmade+Phalaenopsis+Silk+Orchid+Floral+Arrangement+in+Pot.jpg",
    },
    {
      id: 35,
      latin: "Caryota Mitis",
      common: "Fish Tail Palm",
      category: "Palm",
      tempmax: 77,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Frequent",
      image:
        "https://cb.scene7.com/is/image/Crate/PottedFishTailPalmSSS23/$web_pdp_main_carousel_med$/221111145008/potted-faux-fishtail-palm-tree-6.5.jpg",
    },
    {
      id: 39,
      latin: "Chamaedorea Elegans",
      common: "Bella Palm",
      category: "Palm",
      tempmax: 82.4,
      tempmin: 41,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Average",
      image:
        "https://www.ikea.com/us/en/images/products/chamaedorea-elegans-potted-plant-parlor-palm__0121094_pe277873_s5.jpg?f=xs",
    },
    {
      id: 43,
      latin: "Chamaedorea Seifrizii",
      common: "Reed Palm",
      category: "Palm",
      tempmax: 50,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Average",
      image: "https://m.media-amazon.com/images/I/91aqkyr0jjL._AC_SL1500_.jpg",
    },
    {
      id: 49,
      latin: "Chamaedorea Erumpens",
      common: "Bamboo Palm",
      category: "Palm",
      tempmax: 82.4,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Average",
      image: "https://www.plantscape.com/Images/PSG-2016/bamboopalm14.jpg",
    },
    {
      id: 58,
      latin: "Chamaedorea Metallica",
      common: "Miniature Fishtail",
      category: "Palm",
      tempmax: 50,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Average",
      image:
        "https://static.wixstatic.com/media/0906d2_9e8b8c7c8e1a452895d19fe457e07a39~mv2.webp",
    },
    {
      id: 74,
      latin: "Cycas Revoluta",
      common: "Sago Palm",
      category: "Palm",
      tempmax: 46.4,
      tempmin: 20,
      ideallight: "Prefers Bright, Indirect Sunlight",
      toleratedlight: "Partial Shade",
      watering: "Less Frequent",
      image:
        "https://cdn.webshopapp.com/shops/30495/files/416531287/cycas-cycas-revoluta-king-sago-palm.jpg",
    },
    {
      id: 89,
      latin: "Dypsis Lutescens",
      common: "Butterfly Palm",
      category: "Palm",
      tempmax: 82.4,
      tempmin: 50,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Frequent",
      image:
        "https://www.brighterblooms.com/cdn/shop/products/Areca_Palm_2_BB.jpg?v=1638144873&width=650",
    },
    {
      id: 128,
      latin: "Pachypodium Geayi",
      common: "Madagascar Palm",
      category: "Cactus And Succulent",
      tempmax: 95,
      tempmin: 46.4,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Infrequent",
      image: "https://mygardenlife.com/wp-content/uploads/2022/12/6882_9-2.jpg",
    },
    {
      id: 2,
      latin: "Aechmea Fatsiata",
      common: "Silver Vase",
      category: "Bromeliad",
      tempmax: 53.6,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Partial Shade",
      watering: "Less Frequent",
      image:
        "https://i0.wp.com/laidbackgardener.blog/wp-content/uploads/2016/01/20160111a.jpg?w=380&ssl=1",
    },
    {
      id: 70,
      latin: "Cryptanthus Rose Elaine",
      common: "Earth Star",
      category: "Bromeliad",
      tempmax: 82.4,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Direct Sunlight",
      watering: "Average",
      image:
        "https://www.tropicopia.com/house-plant/originals/Cryptanthus%20Rose%20Eliane%2004.jpg",
    },
    {
      id: 94,
      latin: "Guzmania",
      common: "Guzmania Sunnytime",
      category: "Bromeliad",
      tempmax: 50,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Partial Shade",
      watering: "Less Frequent",
      image:
        "https://olivehill.net/wp-content/uploads/2018/10/06GuzmaniaGeorgia-800x800.jpg",
    },
    {
      id: 96,
      latin: "Guzmania",
      common: "Guzmania Empire",
      category: "Bromeliad",
      tempmax: 50,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Partial Shade",
      watering: "Less Frequent",
      image:
        "https://succulentsbox.com/cdn/shop/files/29_a9e47b3f-d97f-40cf-843d-60cb6218cabe_2000x.jpg?v=1697013909",
    },
    {
      id: 101,
      latin: "Guzmania",
      common: "Claret",
      category: "Bromeliad",
      tempmax: 50,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Partial Shade",
      watering: "Less Frequent",
      image:
        "https://cdn.shopify.com/s/files/1/0068/4215/5090/t/115/assets/4b7badba6c9b--PL-BromeliadCLaire-6IN-po-lr-gray_730x.jpg?v=1633120877",
    },
    {
      id: 108,
      latin: "Guzmania",
      common: "Mariposa",
      category: "Bromeliad",
      tempmax: 50,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Less Frequent",
      image:
        "https://endanea.com/wp-content/uploads/2021/01/guzmania-planta-con-flor-570x718.jpg",
    },
    {
      id: 110,
      latin: "Guzmania",
      common: "Marjan",
      category: "Bromeliad",
      tempmax: 50,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Partial Shade",
      watering: "Less Frequent",
      image:
        "https://westbrae-nursery.com/cdn/shop/products/GuzmaniaMarjan6in_900x.jpg?v=1582260214",
    },
    {
      id: 112,
      latin: "Guzmania",
      common: "Rana",
      category: "Bromeliad",
      tempmax: 50,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Less Frequent",
      image:
        "https://olivehill.net/wp-content/uploads/2015/08/08GuzmaniaLisa3ppp6-1-800x800.jpg",
    },
    {
      id: 114,
      latin: "Euphorbia Drupifera",
      common: "Spurge",
      category: "Cactus And Succulent",
      tempmax: 95,
      tempmin: 53.6,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Infrequent",
      image:
        "https://www.sunshinetropical.com/wp-content/uploads/2018/07/14-EUP-DRUP-GREEN-GIANT.jpg",
    },
    {
      id: 128,
      latin: "Pachypodium Geayi",
      common: "Madagascar Palm",
      category: "Cactus And Succulent",
      tempmax: 95,
      tempmin: 46.4,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Infrequent",
      image: "https://mygardenlife.com/wp-content/uploads/2022/12/6882_9-2.jpg",
    },
    {
      id: 3,
      latin: "Agave Angustilolia Marginata",
      common: "Century Plant",
      category: "Cactus And Succulent",
      tempmax: 95,
      tempmin: 41,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Infrequent",
      image:
        "https://assets.wfcdn.com/im/75588655/resize-h445%5Ecompr-r85/2443/244329906/Christie+27%27%27+Faux+Agave+Plant+in+Pot.jpg",
    },
    {
      id: 6,
      latin: "Agave Filifera",
      common: "Thread Agave",
      category: "Cactus And Succulent",
      tempmax: 95,
      tempmin: 41,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Infrequent",
      image:
        "https://littleprinceplants.com/wp-content/uploads/2020/01/Agave-Royal-Flush-scaled.jpg.webp",
    },
    {
      id: 8,
      latin: "Agave Attenuata",
      common: "Dragon Tree Agave",
      category: "Cactus And Succulent",
      tempmax: 95,
      tempmin: 41,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Infrequent",
      image:
        "https://images.squarespace-cdn.com/content/v1/5968af67414fb590cb8f77e3/1562315482549-2UA9IUI99VLE28OCSWNV/81HW-rmnO1L._SL1500_.jpg?format=1500w",
    },
    {
      id: 19,
      latin: "Agave Verschaffeltii",
      common: "Blue Agave",
      category: "Cactus And Succulent",
      tempmax: 95,
      tempmin: 53.6,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Infrequent",
      image:
        "https://d2j6dbq0eux0bg.cloudfront.net/images/9347649/3374012011.jpg",
    },
    {
      id: 22,
      latin: "Agave Striata",
      common: "Lilliput Agave",
      category: "Cactus And Succulent",
      tempmax: 95,
      tempmin: 53.6,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Infrequent",
      image:
        "https://www.seeds-gallery.com/8586-large_default/sporoi-agave-striata.jpg",
    },
    {
      id: 37,
      latin: "Cereus Peruvianus",
      common: "Tree Cereus",
      category: "Cactus And Succulent",
      tempmax: 95,
      tempmin: 41,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Infrequent",
      image:
        "https://m.media-amazon.com/images/I/81vahJcrIUL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    },
    {
      id: 34,
      latin: "Anthurium Superbum",
      common: "Bronze Anthurium",
      category: "Anthurium",
      tempmax: 82.4,
      tempmin: 64.4,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Less Frequent",
      image:
        "https://shoptansy.com/cdn/shop/products/image_c5557f9d-94ee-4c73-9227-d66d048c60b2_720x.jpg?v=1631049471",
    },
    {
      id: 45,
      latin: "Anthurium X",
      common: "Tailflower",
      category: "Anthurium",
      tempmax: 71.6,
      tempmin: 64.4,
      ideallight: "Bright light",
      toleratedlight: "Diffused",
      watering: "Less Frequent",
      image:
        "https://cdn-folnc.nitrocdn.com/fmzeQfhBETiKkxuuwSMibDGzEKvFOImH/assets/images/optimized/rev-529a1dc/culturedplants.com/wp-content/uploads/2022/06/Anthurium-crystallinum-x-forgetii-2.jpg",
    },
    {
      id: 46,
      latin: "Anthurium Hookeri",
      common: "Bird Nest Anthurium",
      category: "Anthurium",
      tempmax: 82.4,
      tempmin: 64.4,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Less Frequent",
      image:
        "https://okanoka.com/cdn/shop/products/582814-wm-16915.5_watermarked_1024x1024@2x.jpg?v=1664713527",
    },
    {
      id: 57,
      latin: "Anthurium Schlechtendalii",
      common: "Cabbage Anthurium",
      category: "Anthurium",
      tempmax: 82.4,
      tempmin: 64.4,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Less Frequent",
      image:
        "https://www.thejunglecollective.com.au/wp-content/uploads/2020/05/Anthurium-Schlechtendalii-200mm-s.jpg.webp",
    },
    {
      id: 62,
      latin: "Anthurium Hookeri",
      common: "Birds Nest Anthurium",
      category: "Anthurium",
      tempmax: 82.4,
      tempmin: 64.4,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Less Frequent",
      image:
        "https://i.etsystatic.com/23242079/r/il/8cada3/3737512943/il_794xN.3737512943_krx7.jpg",
    },
    {
      id: 41,
      latin: "Calathea Pictura Argentea",
      common: "Silver Calathea",
      category: "Foliage Plant",
      tempmax: 77,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Average",
      image: "https://m.media-amazon.com/images/I/81RzBbD-i3L._AC_SX679_.jpg",
    },
    {
      id: 36,
      latin: "Codiaeum Petra",
      common: "Croton",
      category: "Foliage Plant",
      tempmax: 82.4,
      tempmin: 50,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Average",
      image:
        "https://nurserynisarga.in/wp-content/uploads/2023/02/Buy-Croton-Petra-Plant-Online.webp",
    },
    {
      id: 40,
      latin: "Calathea Veitchiana",
      common: "Medallion Calathea",
      category: "Foliage Plant",
      tempmax: 77,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Average",
      image:
        "https://www.lightbulbs.com/catalog/product_photos/Vickerman/724460md.jpg",
    },
    {
      id: 50,
      latin: "Calathea Stromata",
      common: "Stromante",
      category: "Foliage Plant",
      tempmax: 77,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Average",
      image:
        "https://plantworldlondon.com/wp-content/uploads/2021/06/Calathea-Ornata-Sanderiana-1.jpg",
    },
    {
      id: 51,
      latin: "Codiaeum",
      common: "Garden Croton",
      category: "Foliage Plant",
      tempmax: 82.4,
      tempmin: 50,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Average",
      image:
        "https://shopyarrow.com/cdn/shop/products/Yarrow.Shop_Houseplant_Plant_-74_860x.jpg?v=1607985340",
    },
    {
      id: 60,
      latin: "Calathea Ornata Rosea Lineata",
      common: "Stiped Calathea",
      category: "Foliage Plant",
      tempmax: 77,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Average",
      image:
        "https://heyrooted.com/cdn/shop/products/8CALATHEA_PINSTRIPE-2_d3b7b69e-a4db-46e7-8a34-81cf04608653.jpg?v=1677282975&width=713",
    },
    {
      id: 76,
      latin: "Ctenanthe Lubbersiana",
      common: "Phrynium",
      category: "Foliage Plant",
      tempmax: 77,
      tempmin: 53.6,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Frequent",
      image:
        "https://i0.wp.com/www.halaplants.ae/wp-content/uploads/2021/04/Ctenanthe-lubbersiana-19L.jpg?fit=800%2C800&ssl=1",
    },
    {
      id: 132,
      latin: "Liriope Muscari Variegata",
      common: "Variegated Lily Turf",
      category: "Foliage Plant",
      tempmax: 46.4,
      tempmin: 20,
      ideallight: "Bright Light",
      toleratedlight: "Direct Sunlight",
      watering: "Average",
      image:
        "https://treemart.org/wp-content/uploads/2023/03/Liriope.-asst.webp",
    },
    {
      id: 3001,
      latin: "Anthurium Andraeanum",
      common: "Flamingo Lily",
      category: "Anthurium",
      tempmax: 75,
      tempmin: 65,
      ideallight: "6 or more hours of indirect sunlight per day",
      toleratedlight: "Partial Shade",
      watering: "Average",
      image:
        "https://naturerabbit.in/wp-content/uploads/2018/11/Nature-Rabbit-Anthurium-Pink-Plant.jpg",
    },
    {
      id: 3002,
      latin: "Bougainvillea Glabra",
      common: "Lesser Bougainvillea",
      category: "Flower",
      tempmax: 95,
      tempmin: 68,
      ideallight: "6 or more hours of indirect sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Less Frequent",
      image: "https://m.media-amazon.com/images/I/81BuUSq6tfL._AC_SL1500_.jpg",
    },
    {
      id: 3003,
      latin: "Chamaedorea Elegans",
      common: "Parlor Palm",
      category: "Palm",
      tempmax: 80,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Direct Sunlight",
      watering: "Less Frequent",
      image:
        "https://target.scene7.com/is/image/Target/GUEST_e4a9b2b3-e80c-4344-bbe7-588ebdbe9d79?wid=1200&hei=1200&qlt=80&fmt=webp",
    },
    {
      id: 3004,
      latin: "Cryptanthus Elaine",
      common: "Starfish Plant",
      category: "Bromeliad",
      tempmax: 85,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Partial Shade",
      watering: "Average",
      image:
        "https://bullisbrom.com/wp-content/uploads/2016/05/Web-Elaine-Gallery-MAIN.jpg",
    },
    {
      id: 3005,
      latin: "Adiantum Capillus Veneris",
      common: "Southern Maidenhair Fern",
      category: "Fern",
      tempmax: 75,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Diffused",
      watering: "Frequent",
      image:
        "https://hips.hearstapps.com/goodhousekeeping-uk/main/embedded/30528/fern.jpg?resize=980:*",
    },
    {
      id: 3007,
      latin: "Echinocactus Grusonii",
      common: "Golden Barrel Cactus",
      category: "Cactus And Succulent",
      tempmax: 75,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Direct Sunlight",
      watering: "Infrequent",
      image:
        "https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/81veoB+GFiL._SX679_.jpg",
    },
    {
      id: 3008,
      latin: "Calathea Veitchiana",
      common: "Prayer Plant",
      category: "Foliage Plant",
      tempmax: 75,
      tempmin: 50,
      ideallight: "Bright Light",
      toleratedlight: "Partial Shade",
      watering: "Average",
      image:
        "https://microplantstudio.com/wp-content/uploads/2020/03/Calathea-Medallion.jpg",
    },
    {
      id: 3009,
      latin: "Asparagus Aethiopicus",
      common: "Foxtail Fern",
      category: "Fern",
      tempmax: 75,
      tempmin: 40,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Partial Shade",
      watering: "Average",
      image:
        "https://i.etsystatic.com/20630033/r/il/675e2c/3735549616/il_570xN.3735549616_6e5q.jpg",
    },
    {
      id: 3010,
      latin: "Nephrolepis Obliterata",
      common: "Kimberly Queen Fern",
      category: "Fern",
      tempmax: 70,
      tempmin: 40,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Partial Shade",
      watering: "Average",
      image:
        "https://interiorfoliage.com/cdn/shop/products/Fern_Basket_1024x1024.jpg?v=1499462573",
    },
    {
      id: 3011,
      latin: "Saintpaulia Ionantha",
      common: "African Violet",
      category: "Flower",
      tempmax: 80,
      tempmin: 60,
      ideallight: "Indirect Sunlight",
      toleratedlight: "Partial Shade",
      watering: "Less Frequent",
      image:
        "https://media.istockphoto.com/id/180886881/photo/violet.jpg?s=612x612&w=0&k=20&c=-rolQ_M4xR-YFtCZYjg1X6S3qh3VR8K42vQ24_iquM4=",
    },
    {
      id: 3012,
      latin: "Narcissus",
      common: "Daffodil",
      category: "Flower",
      tempmax: 65,
      tempmin: 30,
      ideallight: "6 or more hours of direct sunlight per day",
      toleratedlight: "Direct Sunlight",
      watering: "Frequent",
      image: "https://cdn.atwilltech.com/flowerdatabase/p/PL03203LG.425.jpg",
    },
    {
      id: 3013,
      latin: "Strelitzia Reginae",
      common: "Bird Of Paradise",
      category: "Palm",
      tempmax: 85,
      tempmin: 50,
      ideallight: "Bright Sunlight",
      toleratedlight: "Partial Shade",
      watering: "Average",
      image:
        "https://cdn.thestem.co.uk/production/imager-transforms/digitaloceanspaces/product-images/plants/bird-of-paradise/133383/Bird-of-Paradise-White-fibreclay-pot_c6832acb27c72430f782d679cd672ef1.webp",
    },
    {
      id: 3014,
      latin: "Anthurium Warocqueanum",
      common: "Queen Anthurium",
      category: "Anthurium",
      tempmax: 85,
      tempmin: 50,
      ideallight: "Bright Sunlight",
      toleratedlight: "Diffused",
      watering: "Average",
      image:
        "https://twopeasinacondo.com/wp-content/uploads/2021/09/queen-anthurium-warocqueanum-in-white-pots-1.jpg",
    },
    {
      id: 3015,
      latin: "Anthurium Falcatum",
      common: "Tesla Plants",
      category: "Anthurium",
      tempmax: 85,
      tempmin: 50,
      ideallight: "Bright Sunlight",
      toleratedlight: "Diffused",
      watering: "Average",
      image:
        "https://ecuageneraus.com/cdn/shop/files/Anthuriumfalcatumaffplant_700x700.heic?v=1697480909",
    },
    {
      id: 3016,
      latin: "Anthurium Exstipulatum",
      common: "Walking Anthurium",
      category: "Anthurium",
      tempmax: 95,
      tempmin: 50,
      ideallight: "Bright Sunlight",
      toleratedlight: "Diffused",
      watering: "Average",
      image:
        "https://tropicalsplants.com/1016-large_default/anthurium-salgarense.jpg",
    },
  ],
};

module.exports = plantData;
